// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLSkhtYw40R3d5e-9cw-yJZV4BjzHyhMI',
    appId: '1:154713069402:web:2b98a766ca6b40f9638563',
    messagingSenderId: '154713069402',
    projectId: 'wander-5dde9',
    authDomain: 'wander-5dde9.firebaseapp.com',
    storageBucket: 'wander-5dde9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskXA7OTaHpsSFr4oEzC0bza7khU1YQ7M',
    appId: '1:154713069402:android:9cd32374978f6831638563',
    messagingSenderId: '154713069402',
    projectId: 'wander-5dde9',
    storageBucket: 'wander-5dde9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DdNOS7KmuJORMTlfYIvJyeteyt2ONSw',
    appId: '1:154713069402:ios:1f28d80ef2026f55638563',
    messagingSenderId: '154713069402',
    projectId: 'wander-5dde9',
    storageBucket: 'wander-5dde9.firebasestorage.app',
    iosBundleId: 'com.example.wander',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1DdNOS7KmuJORMTlfYIvJyeteyt2ONSw',
    appId: '1:154713069402:ios:d0281a2d443e054c638563',
    messagingSenderId: '154713069402',
    projectId: 'wander-5dde9',
    storageBucket: 'wander-5dde9.firebasestorage.app',
    iosBundleId: 'wander-5dde9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLSkhtYw40R3d5e-9cw-yJZV4BjzHyhMI',
    appId: '1:154713069402:web:e68eaf6733f5d2c3638563',
    messagingSenderId: '154713069402',
    projectId: 'wander-5dde9',
    authDomain: 'wander-5dde9.firebaseapp.com',
    storageBucket: 'wander-5dde9.firebasestorage.app',
  );
}
